JsonExtractor/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JsonExtractor.Models
{
    public class Booking
    {
        public string ARRIVAL_DATE { get; set; }
        public string DEPARTURE_DATE { get; set; }
        public float PRICE { get; set; }
        public string CURRENCY { get; set; }
        public string RATENAME { get; set; }
        public int ADULTS { get; set; }
        public int BREAKFAST_INCLUDED { get; set; }

    }
}

JsonExtractor/Controllers/ExtractionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using JsonExtractor.Models;

namespace JsonExtractor.Controllers
{
    public class ExtractionController : Controller
    {
        public ActionResult Extract()
        {

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Extract(HttpPostedFileBase file)
        {
            try
            {
                IEnumerable<Booking> bookings;
                if (file != null && file.ContentLength > 0)
                {
                    using (StreamReader stream = new StreamReader(file.InputStream))
                    {

                        bookings = await GetBookingsFromFile(stream);

                        string content = Logic.TaskLogic.RenderExcelContent(bookings);
                        Response.ClearContent();
                        Response.Buffer = true;
                        Response.AddHeader("content-disposition", "attachment; filename=Report.xls");
                        Response.ContentType = "application / vnd.openxmlformats - officedocument.spreadsheetml.sheet";
                        Response.Output.Write(content);

                        Response.Charset = "";
                        Response.Flush();
                        Response.End();
                    }

                }
                else
                {
                    throw new Exception("File not found or empty.");
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                return View("../Shared/Error");
            }


        }

        public async Task<IEnumerable<Booking>> GetBookingsFromFile(StreamReader stream)
        {
            try
            {
                string jsonContent = await stream.ReadToEndAsync();
                return Logic.TaskLogic.ReadJason(jsonContent);
            }
            catch (Exception)
            {
                throw;
            }

        }



    }
}

JsonExtractor/Views/Extraction/Extract.cshtml
@{
    ViewBag.Title = "Task2 - Reporting";
}

<div class="jumbotron">
    <h1>Task2 - Reporting</h1>
</div>

<div class="row">
    <div class="col-md-4">
      

        @using (Html.BeginForm("Extract", "Extraction", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <h2>Upload file</h2>
            <input type="file" name="file" id="file" />

            <input type="submit" class="btn btn-default" />
        }

    </div>
   
</div>

JsonExtractor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Json Extractor</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
 
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Json Extractor - Jasmina Draskovic</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>